site_name: YOUR_PROJECT_NAME
site_description: Add your description here
site_author: Your Name
site_url: https://your-github-username.github.io/your-repo-name/

repo_name: your-github-username/your-repo-name
repo_url: https://github.com/your-github-username/your-repo-name

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search

nav:
  - Home: index.md
  - API: api.md
  - Development: development.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true 