name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv
        uv sync --dev

    - name: Run linting
      run: |
        source .venv/bin/activate
        nox -s lint

    - name: Run formatting check
      run: |
        source .venv/bin/activate
        nox -s format_code

    - name: Run type checking
      run: |
        source .venv/bin/activate
        nox -s typing

    - name: Run tests
      run: |
        source .venv/bin/activate
        nox -s test

    - name: Run security checks
      run: |
        source .venv/bin/activate
        nox -s security

  docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --extra docs

    - name: Build documentation
      run: |
        source .venv/bin/activate
        nox -s docs
